Importing the libraries

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [29]:
data = pd.read_csv("Data.csv")
print(data)


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [30]:
X = data.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [31]:
y = data.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

Missing Data

In [32]:
# from sklearn.preprocessing import Imputer

# imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
# y_imputed = imputer.fit(X[:, 1:3])
# X[:, 1:3] = y_imputed.transform(X[:, 1:3])
# X

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
y_imputed = imputer.fit_transform(X[:, 1:3])
X[:, 1:3] = y_imputed
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Categorical data

In [33]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [34]:
# label_encoder_X = LabelEncoder()
# X[:, 0] = label_encoder_X.fit_transform(X[:, 0])
# one_hot_encoder_X = OneHotEncoder(categorical_features=[0])
# X = one_hot_encoder_X.fit_transform(X).toarray()
# X

from sklearn.compose import ColumnTransformer

label_encoder_X = LabelEncoder()
# Step 1: Label Encoding for the first column
# turns countries into encoded numbers
X[:, 0] = label_encoder_X.fit_transform(X[:, 0])

# Create a column transformer to handle the categorical column
# Step 2: One-Hot Encoding for the first column
# Use ColumnTransformer to apply OneHotEncoder to the first column (index 0)    
categorical_transformer = OneHotEncoder()
one_hot_encoder_X = ColumnTransformer(
    transformers=[('onehot', categorical_transformer, [0])], # transformer was categorical
    remainder='passthrough'
    )

# Apply the preprocessing to the entire dataset
X = one_hot_encoder_X.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [35]:
label_encoder_y = LabelEncoder()
y = label_encoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [36]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [37]:
X_dataframe = pd.DataFrame(X)
y_series = pd.Series(y)
encoded = pd.concat([X_dataframe, y_series], axis=1)
encoded

0    1    2          3             4  0
0  1.0  0.0  0.0       44.0       72000.0  0
1  0.0  0.0  1.0       27.0       48000.0  1
2  0.0  1.0  0.0       30.0       54000.0  0
3  0.0  0.0  1.0       38.0       61000.0  0
4  0.0  1.0  0.0       40.0  63777.777778  1
5  1.0  0.0  0.0       35.0       58000.0  1
6  0.0  0.0  1.0  38.777778       52000.0  0
7  1.0  0.0  0.0       48.0       79000.0  1
8  0.0  1.0  0.0       50.0       83000.0  0
9  1.0  0.0  0.0       37.0       67000.0  1

Splitting the Dataset

In [40]:
# training 80% / testing 20%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=0)

In [41]:
X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [42]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [43]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [44]:
y_test

array([0, 0])

Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)